language: python
python: '2.7'
services:
- rabbitmq
before_install:
- sudo apt-get install python-software-properties
- sudo add-apt-repository -y cloud-archive:icehouse
- sudo apt-get update -qq
install:
- sudo pip install ansible
- '{ echo ''[defaults]''; echo ''roles_path = ../''; } >> ansible.cfg'
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
notifications:
  slack:
    secure: G4COdO2aRQEnFOU+AMMcrCAL6zazzxcfV3i60FH1jdjjc95VROXYbnzpPU1Di46s9QTx83pKRrlBbWWXXy9B3YllxQveVsJyMHLQe39ilE/DkCQYA4HzgKLUaoNupBg2K2zoC/RqvyruMwbl6SRfgs8elaCwnUpNv790Pls4lekyoStFHIYpYS7BdX/Qf7ZffSE8fzMtlcvkjTXGs5Drq5t6Z7Zf5c66R7FcWq83bvd2ssWIqt6EeT5w6+c2JRHcUdSyGgL0HlOe7n19gIxuQ0C+ZLYYDQ+lHRkIFLgWks9+9tFdPDo9a7OKKgV3MVpOO2fHcs3296I4BkJ/+YNNNC4Jh7u/lNvPoHVMbA+fsdALmRymMu3+8OkD+NBGf+JlDTCBJGMmpMpLkoTgJHogYF2gX8dAPxxi/dQqF7dYt/umd24IL+WSBy8I/uJzhVaVvEBEslS3NKTWYQdvUtqVT4dOCqpEP4IZ/XZYyMZ6RUVP7AR06UcrTkrDt/ggYAoOuOMi1S6QIqn4o5Nra0SGTnozk/Md14/JuDLeDmmrHGUVxBgDg2cYUN+XmFha4yn8+K2m3ZVfnykaUNUyRdQ+5ppOijJ3vFKUAExuCnKSE93c13y5CUqPt0ji63BItuhh3K+QfO0u64STBj1Oy5UI7oVyqG1CdFWv3mpw9ZWWye0=
