---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure Nova Compute
  ini_file: dest=/etc/nova/nova.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    # Common settings
    - section:  DEFAULT
      option:   my_ip
      value:    "{{ nova_compute_my_ip }}"
    - section:  DEFAULT
      option:   log_dir
      value:    "{{ nova_compute_log_dir }}"
    - section:  DEFAULT
      option:   debug
      value:    "{{ nova_compute_log_debug }}"
    - section:  DEFAULT
      option:   verbose
      value:    "{{ nova_compute_log_verbose }}"
    # RabbitMQ
    - section:  DEFAULT
      option:   rpc_backend
      value:    rabbit
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ nova_compute_rabbit_userid }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ nova_compute_rabbit_password }}"
    - section:  DEFAULT
      option:   rabbit_virtual_host
      value:    "{{ nova_compute_rabbit_virtual_host }}"
    - section:  DEFAULT
      option:   rabbit_retry_interval
      value:    "{{ nova_compute_rabbit_retry_interval }}"
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ nova_compute_rabbit_host }}"
    - section:  DEFAULT
      option:   rabbit_port
      value:    "{{ nova_compute_rabbit_port }}"
    - section:  DEFAULT
      option:   rabbit_hosts
      value:    "{{ nova_compute_rabbit_hosts }}"
    - section:  DEFAULT
      option:    rabbit_ha_queues
      value:    "{{ nova_compute_rabbit_ha_queues }}"
    # Nova novnc
    - section:  DEFAULT
      option:   vnc_enabled
      value:    True
    - section:  DEFAULT
      option:   vncserver_listen
      value:    "{{ nova_compute_vncserver_listen }}"
    - section:  DEFAULT
      option:   vncserver_proxyclient_address
      value:    "{{ nova_compute_vncserver_proxyclient_address }}"
    - section:  DEFAULT
      option:   novncproxy_base_url
      value:    "{{ nova_compute_novncproxy_base_url }}"
    # Memcached
    - section:  DEFAULT
      option:   memcached_servers
      value:    "{{ nova_compute_memcached_servers }}"
    # Neutron
    - section:  DEFAULT
      option:   network_api_class
      value:    nova.network.neutronv2.api.API
    - section:  DEFAULT
      option:   neutron_url
      value:    "{{ neutron_protocol }}://{{ neutron_hostname }}:{{ neutron_port }}"
    - section:  DEFAULT
      option:   neutron_auth_strategy
      value:    keystone
    - section:  DEFAULT
      option:   neutron_admin_tenant_name
      value:    service
    - section:  DEFAULT
      option:   neutron_admin_username
      value:    neutron
    - section:  DEFAULT
      option:   neutron_admin_password
      value:    "{{ neutron_pass }}"
    - section:  DEFAULT
      option:   neutron_admin_auth_url
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_admin_port }}/v2.0"
    - section:  DEFAULT
      option:   linuxnet_interface_driver
      value:    nova.network.linux_net.LinuxOVSInterfaceDriver
    - section:  DEFAULT
      option:   firewall_driver
      value:    nova.virt.firewall.NoopFirewallDriver
    - section:  DEFAULT
      option:   security_group_api
      value:    neutron
    # Keystone
    - section:  DEFAULT
      option:   auth_strategy
      value:    keystone
    - section:  keystone_authtoken
      option:   auth_uri
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_port }}/v2.0"
    - section:  keystone_authtoken
      option:   auth_host
      value:    "{{ keystone_hostname }}"
    - section:  keystone_authtoken
      option:   auth_port
      value:    "{{ keystone_port }}"
    - section:  keystone_authtoken
      option:   auth_protocol
      value:    "{{ keystone_protocol }}"
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    nova
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ nova_compute_pass }}"
    # Glance
    - section:  DEFAULT
      option:   glance_host
      value:    "{{ glance_hostname }}"
    - section:  DEFAULT
      option:   glance_port
      value:    "{{ glance_port }}"
    - section:  DEFAULT
      option:   glance_protocol
      value:    "{{ glance_protocol }}"
  notify:
    - Restart Nova Compute

- name: Configure Nova Compute (HV)
  ini_file: dest=/etc/nova/nova-compute.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section: libvirt
      option:  virt_type
      value:   "{{ nova_compute_virt_type}}"
  notify:
    - Restart Nova Compute
